return commit_ts in the function 'commit()' in txn.py
dgraph-io/pydgraph pull request #213
Opened 2023-10-07 01:16 UTC by seedoilz

I also modified the example(simple.py) to show how to print the commit_ts

2023-10-07 01:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/pydgraph?pullRequest=213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/pydgraph?pullRequest=213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/pydgraph?pullRequest=213) it.</sub>

2023-10-07 17:51 UTC, matthewmcneely requested changes

2023-10-07 17:51 UTC, matthewmcneely commented on pydgraph/txn.py
> +            return self._dc.commit_or_abort(self._ctx, timeout=timeout,
For completeness, I think the `commit_or_abort` attempt on line 246 should also return as this does (in those instances where the jwt token has expired but a re-login was successful)

2023-10-08 17:54 UTC, matthewmcneely commented
@joshua-goldstein This seems like a no-brainer, can you have a look?

2023-10-08 17:55 UTC, matthewmcneely approved these changes

2023-10-13 21:43 UTC, joshua-goldstein approved these changes
Thanks for the PR @seedoilz

2023-10-13 21:44 UTC, merged